### ISSUE TITLE
Timestamp for date range of value

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-micromobility-api#23]
Could we add info to the geojson that provides a time range for the trips being served. On the frontend, we'd then need to display this date range for users.

*Migrated to [atd-data-tech #1785](https://github.com/cityofaustin/atd-data-tech/issues/1785)*

**Comment by johnclary** [comment]
will metadata key to API and 
- start date
- end dates
- license
- update date
- repo url
