### ISSUE TITLE
Mode param value is not working

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-micromobility-api#36]
As reported [here](https://github.com/cityofaustin/transportation-dockless-dataviz/issues/84).

Changing the `mode` parameter does not affect the result of the data returned by the API.

**Comment by johnclary** [comment]
Obvious that the `mode` parameter is completely absent from the `WHERE` clause of the Socrata request:
https://github.com/cityofaustin/transportation-dockless-api/blob/master/app/app.py#L136

Some idiot broke this.

**Comment by mateoclarke** [comment]
And another idiot reviewed the code and also didn't notice. Don't be so hard on yourself homie 😄
