### ISSUE TITLE
dockless-api.austintexas.io/ does not exist/ is down

### ISSUE THREAD

**Issue by MrRorschach** [cityofaustin/atd-micromobility-api#45]
When trying to query the API or visit a site such as https://dockless-api.austintexas.io/v1/trips?xy=-97.75094341278084,30.276185988411257&flow=destination Chrome/Firefox/Safari return DNS error saying site cannot be resolved. Is this site currently live?

**Comment by johnclary** [comment]
The url is [http://dockless-data.austintexas.io](http://dockless-data.austintexas.io). 

So, this works: https://dockless-data.austintexas.io/v1/trips?xy=-97.75094341278084,30.276185988411257&flow=destination

I suppose we should document that somewhere.

**Comment by MrRorschach** [comment]
Thanks, reference.md still says [dockless-api.austintexas.io](dockless-api.austintexas.io) instead of [dockless-data.austintexas.io](dockless-data.austintexas.io)

I was going to submit a PR, but over here at ACC we use bitbucket and my work machine doesn't have my github credentials.
