### ISSUE TITLE
Switch to Census Tract Querying

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-micromobility-api#48]
As discussed [here](https://github.com/cityofaustin/atd-dockless-processing/issues/6), were' switching to census tract geographies for trip origins and destinations. The API needs to be updated accordingly.

Todo:
- [x] update variable and json key names
- [x] create "indexed" census tract geojson

**Comment by johnclary** [comment]
Todo:
- update variable and json key names
- create "indexed" census tract geojson

**Comment by mateoclarke** [comment]
Closed with https://github.com/cityofaustin/atd-dockless-api/pull/49
